# WARNING: Make sure the project-folder-name is unique on your server!
# You should disable port-exposure in production!

networks:
    app:
        external: false

volumes:
    db_volume:
        driver: local
    redis_volume:
        driver: local

services:
    php:
        container_name: ${APP_NAME}_php
        image: umex/php8.3-laravel-aio:1.1-fpm-alpine
        stop_grace_period: 60s
        volumes:
            - ./:/app
        environment:
            ENV_DEV: true
            DEV_NPM_RUN_DEV: true
            DEV_ENABLE_XDEBUG: true
            ENABLE_SUPERVISOR: true
            ENABLE_HORIZON_WORKER: true
        ports:
            - "8000:8000" # php
            - "5173:5173" # vite
            - "9003:9003" # xdebug
        restart: unless-stopped
        depends_on:
            - mysql
            - redis
        networks:
            - app

    mysql:
        container_name: ${APP_NAME}_mysql
        image: mariadb:lts
        # image: mysql:lts
        command:
            - '--character-set-server=utf8mb4'
            - '--collation-server=utf8mb4_unicode_ci'
            - '--skip-name-resolve' # Disable DNS lookups (not needed in Docker, improves performance)
        volumes:
            - db_volume:/var/lib/mysql/:delegated
        cap_add:
            - SYS_NICE # Allow the container to adjust process priority (optional for performance tuning)
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'false' # Disallow empty password
            MYSQL_INITDB_SKIP_TZINFO: '1' # Skip loading DB time zone tables (improves performance)
            ### Database initialization ###
            MYSQL_ROOT_PASSWORD: ${DB_INIT_ROOT_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        ports:
            - "3306:3306"
        restart: unless-stopped
        networks:
            - app

    redis:
        container_name: ${APP_NAME}_redis
        image: redis:7-alpine
        volumes:
            - redis_volume:/data
        command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
        ports:
            - "6379:6379"
        restart: unless-stopped
        networks:
            - app

#    pma:
#        container_name: ${APP_NAME}_pma
#        image: phpmyadmin/phpmyadmin:latest
#        environment:
#            PMA_HOST: mysql
#            PMA_PORT: 3306
#            APACHE_PORT: 8080
#            UPLOAD_LIMIT: 1G
#        restart: unless-stopped
#        depends_on:
#            - mysql
#        networks:
#            - app

#    wkhtmltopdf:
#        container_name: ${APP_NAME}_wkhtmltopdf
#        image: umex/wkhtmltopdf-microservice:1.2-alpine
#        restart: unless-stopped
#        environment:
#            MAX_BODY: '150mb'
#        networks:
#            - app
