name: Cleanup Images

on:
    workflow_dispatch:
    schedule:
        - cron: '0 3 * * *' # TÃ¤glich um 03:00 Uhr

permissions:
    packages: write

jobs:
    cleanup:
        name: Cleanup Old Images
        runs-on: ubuntu-latest
        steps:
            -   name: Prune untagged images
                uses: snok/container-retention-policy@v3.0.0
                with:
                    image-names: laravel-aio
                    cut-off: 1w
                    keep-n-most-recent: 3
                    account: ${{ github.actor }}
                    token: ${{ secrets.GITHUB_TOKEN }}
                    # Konzentriert sich nur auf Images ohne Tag (die "Leichen")
                    tag-selection: untagged
